apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-backend
  namespace: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: spring-api
  template:
    metadata:
      labels:
        app: spring-api
    spec:
      containers:
      - name: spring-app
        image: "vikt0rinho/backend:8bb57cf1541fa0c6272e0414426c68df293a8961"
        ports:
        - containerPort: 8080
        env:
        - name: SPRING_DATASOURCE_URL
          value: "jdbc:postgresql://postgres-service.database.svc.cluster.local:5432/eldnevniko"
        - name: SPRING_DATASOURCE_USERNAME
          value: "postgres"
        - name: SPRING_DATASOURCE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: db-secret
              key: password