apiVersion: apps/v1
kind: Deployment
metadata:
  name: stafford-chess-backend
  namespace: backend
  labels:
    app: stafford-chess-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: stafford-chess-api
  template:
    metadata:
      labels:
        app: stafford-chess-api
    spec:
      containers:
      - name: fastapi-app
        image: "vikt0rinho/staffordchess-backend:3b37ff584dc4de9424ae5bfb93e77cf60742b55b"
        ports:
        - containerPort: 8000
        resources:
          requests:
            cpu: "100m"
            memory: "128Mi"
          limits:
            cpu: "250m"
            memory: "256Mi"
        envFrom:
        - secretRef:
            name: staffordchess-secret