apiVersion: external-secrets.io/v1
kind: SecretStore
metadata:
  name: vault-backend
  namespace: backend
spec:
  provider:
    vault:
      server: "https://stafford-chess-vault-cluster-public-vault-fdac272f.53a2cb0f.z1.hashicorp.cloud:8200"
      path: "secret"
      version: "v2"
      namespace: "admin"
      auth:
        tokenSecretRef:
          name: vault-token
          key: token
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: staffordchess-secret
  namespace: backend
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault-backend
    kind: SecretStore
  target:
    name: staffordchess-secret
    creationPolicy: Owner
  data:
    - secretKey: DATABASE_URL
      remoteRef:
        key: staffordchess
        property: DATABASE_URL
    - secretKey: JWT_SECRET
      remoteRef:
        key: staffordchess
        property: JWT_SECRET
    - secretKey: MAIL_USERNAME
      remoteRef:
        key: staffordchess
        property: MAIL_USERNAME
    - secretKey: MAIL_PASSWORD
      remoteRef:
        key: staffordchess
        property: MAIL_PASSWORD
    - secretKey: MAIL_FROM
      remoteRef:
        key: staffordchess
        property: MAIL_FROM
