apiVersion: v1
kind: Service
metadata:
  name: stafford-chess-backend-service
  namespace: backend
  labels:
    app: stafford-chess-api
spec:
  selector:
    app: stafford-chess-api
  ports:
  - port: 8000
    targetPort: 8000
    protocol: TCP
  type: ClusterIP