apiVersion: apps/v1
kind: Deployment
metadata:
  name: stafford-chess-frontend
  namespace: frontend
  labels:
    app: stafford-chess-frontend
spec:
  replicas: 0
  selector:
    matchLabels:
      app: stafford-chess-frontend
  template:
    metadata:
      labels:
        app: stafford-chess-frontend
    spec:
      containers:
      - name: stafford-chess-frontend
        image: "vikt0rinho/staffordchess-frontend:968a06ae2c227767ef26bf40a1a96af07b9c58c3"
        ports:
        - containerPort: 80
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "128Mi"
            cpu: "500m"