apiVersion: apps/v1
kind: Deployment
metadata:
  name: stafford-chess-frontend
  namespace: frontend
  labels:
    app: stafford-chess-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: stafford-chess-frontend
  template:
    metadata:
      labels:
        app: stafford-chess-frontend
    spec:
      containers:
      - name: stafford-chess-frontend
        image: "vikt0rinho/staffordchess-frontend:65eade71aadf8e3ef002f705ecf8d564611fac2c"
        ports:
        - containerPort: 80
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "128Mi"
            cpu: "500m"