apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: stafford-chess-frontend
  namespace: argocd
  labels:
    app.kubernetes.io/part-of: stafford-chess
    tier: frontend
spec:
  project: stafford-chess

  source:
    repoURL: https://github.com/TUES-2026-PBL-11-klas/the-four-horsemen-of-coding-StaffordChess.git
    targetRevision: Infrastructure
    path: k8s/frontend

  destination:
    server: https://kubernetes.default.svc
    namespace: frontend

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=true
    retry:
      limit: 3
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 1m

  ignoreDifferences:
    - group: networking.k8s.io
      kind: Ingress
      jsonPointers:
        - /status/loadBalancer