BEGIN;

CREATE TABLE IF NOT EXISTS puzzles (
    id INTEGER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    fen VARCHAR(255) NOT NULL,
    solution VARCHAR(255),
    theme VARCHAR(255),
    rating INTEGER
);

CREATE TABLE IF NOT EXISTS user_puzzle_attempts (
    id INTEGER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    puzzle_id INTEGER NOT NULL REFERENCES puzzles(id) ON DELETE CASCADE,
    is_solved BOOLEAN DEFAULT false,
    solved_at TIMESTAMPTZ
);

COMMIT;
